resilience4j:
  retry:
    instances:
      paymentProviderRetry:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.net.SocketTimeoutException
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
      redisRetry:
        max-attempts: 3
        wait-duration: 500ms
