# Copy this file to src/main/resources/config/momo-secrets.properties and replace values.

payment.momo.secret.partner-code=MOMOLRJZ20181206
payment.momo.secret.access-key=mTCKt9W3eU1m39TW
payment.momo.secret.secret-key=SetA5RDnLHvt51AULf51DyauxUo3kDU6
